# Change these first
owner: bigbang1112 # Your GitHub organization or username, where this repository lives
repo: gbx-tools-uptime # The name of this repository

sites:
  - name: gbx.tools
    url: https://gbx.tools
  - name: explorer.gbx.tools
    url: https://explorer.gbx.tools
  - name: io.gbx.tools
    url: https://io.gbx.tools
  - name: nc.gbx.tools
    url: https://nc.gbx.tools
  - name: uotd.gbx.tools
    url: https://uotd.gbx.tools
  - name: nuget.gbx.tools
    url: https://nuget.gbx.tools
  - name: discord.gbx.tools
    url: https://discord.gbx.tools
    
assignees: # Users to assign downtime issues (optional)
  - BigBang1112

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gbx.tools
  #baseUrl: /gbx-tools-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.gbx.tools
  introTitle: "**Gbx Tools** status page"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
